require('configs.lsp')
require('configs.dap')
require('configs.cmp')
require('configs.rust')
require('configs.colorschemes')
require('configs.lualine')
require('configs.treesitter')
require('configs.dashboard')
require('configs.ui')

